# Generated by Django 2.2.5 on 2020-05-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200530_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amentities',
            new_name='amenities',
        ),
    ]
